[project]
name = "mach3sbitools"
version = "2.0.0"
description = "Specific SBI package for handling MaCh3 Chains"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "sbi",
    "uproot",
    "matplotlib",
    "ipython",
    "ipykernel",
    "ipywidgets",
    "click",
    "arrow"
]

[project.scripts]
sample_mach3 = "mach3sbitools.apps.__main_sample_mach3__:main"
build_posterior = "mach3sbitools.apps.__main_build_posterior__:main"
