[project]
name = "mach3sbitools"
version = "1.0.0"
description = "Specific SBI package for handling MaCh3 Chains"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "sbi",
    "uproot",
    "matplotlib",
    "ipython",
    "ipykernel",
    "ipywidgets",
    "click"
]

[project.scripts]
mach3sbi = "mach3sbitools.apps.__main__mach3sbi__:main"
mach3sbi_model_comp = "mach3sbitools.apps.__main__compare_models__:main"